#! /usr/bin/env bash
set -eu

src=${1:-}
dest=${2:-}
if [[ ! -d $src || ! -d $dest ]]; then
    printf 'usage: %s <pass-dir> <pago-dir>\n\n' "$(basename "$0")"
    printf 'The pago directory must be initialized,'
    printf ' and the pago agent must be running.\n'
    exit 2
fi

cd "$src"
for file in ./*.gpg ./**/*.gpg; do
    no_ext=${file%*.gpg}
    name=${no_ext#./*}
    ${PASS:-pass} show "$name" | ${PAGO:-pago} add "$name" \
        --dir "$dest" \
        --input \
        --no-confirm \
        ;
done
