version: '3'

vars:
  PAGO_AGENT_CMD_DIR: cmd/pago-agent
  PAGO_CMD_DIR: cmd/pago

env:
  CGO_ENABLED: 0

tasks:
  default:
    deps:
      - all

  all:
    desc: 'Build and test everything'
    deps:
      - build
      - test

  build:
    desc: 'Build all components'
    deps:
      - build:bin

  build:bin:
    desc: 'Build all binaries'
    deps:
      - build:pago
      - build:pago-agent

  build:package:
    desc: 'Build a single Go package'
    internal: true
    dir: '{{.PACKAGE}}'
    cmds:
      - 'go build -trimpath # {{.PACKAGE}}'

  build:pago:
    desc: 'Build the pago binary'
    run: once
    cmds:
      - task: build:package
        vars:
          PACKAGE: '{{.PAGO_CMD_DIR}}'
    sources:
      - '*.go'
      - '**/*.go'
    generates:
      - cmd/pago/pago

  build:pago-agent:
    desc: 'Build the pago agent binary'
    run: once
    cmds:
      - task: build:package
        vars:
          PACKAGE: '{{.PAGO_AGENT_CMD_DIR}}'
    sources:
      - '*.go'
      - '**/*.go'
    generates:
      - cmd/pago-agent/pago-agent

  check:
    desc: 'Build, lint, and test everything'
    deps:
      - build
      - lint
      - test

  clean:
    desc: 'Clean up binaries'
    cmds:
      - rm -f {{.PAGO_CMD_DIR}}/pago {{.PAGO_AGENT_CMD_DIR}}/pago-agent

  lint:
    desc: 'Run golangci-lint'
    cmds:
      - golangci-lint run

  release:
    desc: 'Prepare a release'
    deps:
      - build:bin
    cmds:
      - VERSION=$({{.PAGO_CMD_DIR}}/pago version) go run script/release.go

  test:
    desc: 'Run tests'
    deps:
      - build:bin
    cmds:
      - go test ./...
