version: '3'

vars:
  cmd_dir: cmd/pago
  ext: '{{if eq OS "windows"}}.exe{{end}}'

env:
  CGO_ENABLED: 0

tasks:
  default:
    deps:
      - test

  all:
    desc: 'Build and test everything'
    deps:
      - test

  build:
    desc: 'Build all components'
    deps:
      - build_pago

  build_pago:
    dir: '{{.cmd_dir}}'
    desc: 'Build the pago binary'
    cmds:
      - cmd: go build -trimpath
    sources:
      - '*.go'
      - '../../*.go'
    generates:
      - pago

  clean:
    dir: '{{.cmd_dir}}'
    desc: 'Clean up binaries'
    cmds:
      - rm -f pago pago.exe

  release:
    desc: 'Prepare a release'
    deps:
      - build_pago
    cmds:
      - VERSION=$({{.cmd_dir}}/pago{{.ext}} version) go run script/release.go

  test:
    desc: 'Run tests'
    deps:
      - build_pago
    cmds:
      - go test ./...
