version: '3'

vars:
  ext: '{{if eq OS "windows"}}.exe{{end}}'
  pago_agent_cmd_dir: cmd/pago-agent
  pago_cmd_dir: cmd/pago

env:
  CGO_ENABLED: 0

tasks:
  default:
    deps:
      - test

  all:
    desc: 'Build and test everything'
    deps:
      - test

  build:
    desc: 'Build all components'
    deps:
      - build-pago
      - build-pago-agent

  build-pago:
    dir: '{{.pago_cmd_dir}}'
    desc: 'Build the pago executable'
    cmds:
      - cmd: go build -trimpath
    sources:
      - '*.go'
      - '../../**/*.go'
    generates:
      - pago

  build-pago-agent:
    dir: '{{.pago_agent_cmd_dir}}'
    desc: 'Build the pago agent executable'
    cmds:
      - cmd: go build -trimpath
    sources:
      - '*.go'
      - '../../**/*.go'
    generates:
      - pago-agent

  clean:
    desc: 'Clean up executables'
    cmds:
      - rm -f {{.pago_cmd_dir}}/pago{{.ext}} {{.pago_agent_cmd_dir}}/pago-agent{{.ext}}

  release:
    desc: 'Prepare a release'
    deps:
      - build-pago
    cmds:
      - VERSION=$({{.pago_cmd_dir}}/pago{{.ext}} version) go run script/release.go

  test:
    desc: 'Run tests'
    deps:
      - build-pago
      - build-pago-agent
    cmds:
      - go test ./...
